[build]
  command = "npm run build"
  publish = "build"

[context.production.environment]
  REACT_APP_API_URL = "https://urban-ride-web-api.onrender.com/api"
  REACT_APP_SOCKET_URL = "https://urban-ride-web-api.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
